---
title: "final_plots"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

get_data <- function(fname) {
  read_csv(fname, 
           col_names = c('index',
                         0,
                         0.5,
                         0.75,
                         0.875,
                         0.9375)) %>%
  gather(gamma, rmse, -index) %>%
  mutate(state=fname)
}

x <- reduce(map(c('raw_bits', 'pair_bits', 'triple_bits', 'module3'),
                get_data),
            bind_rows) %>%
  mutate(gamma=as.factor(gamma))
x$state <- factor(x$state, levels = c('raw_bits', 'pair_bits', 'triple_bits', 'module3'))
```


```{r include=FALSE}


x %>%
  ggplot(aes(x=index/1000, y=rmse, color=state, fill=state)) +
  geom_smooth(alpha=0.1) +
  theme_bw(base_size = 20) + 
  theme(
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(),
        axis.title.y = element_blank(),
        legend.key=element_blank(),
        legend.title = element_blank(),
        legend.position = c(0.84, 0.25),
        ) +
  labs(x='Time-step (x1000)', title='RMSE smoothed over similar GVFs') +
  facet_wrap(~gamma, labeller = function (x) map(x, function (y) paste('gamma:', y)), scales='free')
ggsave('rmse.pdf', 
       width = 10 * (1 + sqrt(5)) / 2, 
       height = 10)

```
